---
- name: Find named-checkconf
  set_fact:
    named_checkconf: "{{ executable }}"
  with_first_found:
    files:
      - named-checkconf
    paths:
      - /usr/sbin
      - /usr/bin
  loop_control:
    loop_var: executable
    # skip: false
#  ignore_errors: true
- name: Find named-checkzone
  set_fact:
    named_checkzone: "{{ item }}"
  with_first_found:
    files:
      - /usr/sbin/named-checkzone
      - /usr/bin/named-checkzone
  #  skip: false
  # ignore_errors: true

- name: Executables found
  debug:
    msg:
      - "named-checkconf found: {{ named_checkconf }}"
      - "named-checkzone found: {{ named_checkzone }}"
