---
- name: Find named-checkconf
  set_fact:
    named_checkconf: "{{ results.files[0].path }}"
  ansible.buildin.find:
    patterns:
      - named-checkconf
    paths:
      - /usr/sbin
      - /usr/bin
    use_regex: true
  register: results

- name: Find named-checkzone
  set_fact:
    named_checkzone: "{{ results.files[0].path }}"
  ansible.buildin.find:
    patterns:
      - named-checkzone
    paths:
      - /usr/sbin
      - /usr/bin
    use_regex: true
  register: results

- name: Executables found
  debug:
    msg:
      - "named-checkconf found: {{ named_checkconf }}"
      - "named-checkzone found: {{ named_checkzone }}"
