---
- name: Find named-checkconf
  with_first_found:
    files:
      - named-checkconf
    paths:
      - /usr/sbin
      - /usr/bin
  loop_control:
    loop_var: executable
  set_fact:
    named_checkconf: "{{ executable }}"

- name: Set named_conf
  set_fact:
    named_checkconf: "{{ executable }}"

- name: Find named-checkzone
  with_first_found:
    files:
      - /usr/sbin/named-checkzone
      - /usr/bin/named-checkzone
  loop_control:
    loop_var: executable
  set_fact:
    named_checkzone: "{{ executable }}"
  #  skip: false
  # ignore_errors: true

- name: Executables found
  debug:
    msg:
      - "named-checkconf found: {{ named_checkconf }}"
      - "named-checkzone found: {{ named_checkzone }}"
