---
- name: Find named-checkzone
  with_first_found:
    - paths:
        - /usr/sbin
        - /usr/bin
      files:
        - named-checkzone
      skip: true
  register: named_checkzone

- name: Find named-checkconf
  with_first_found:
    - paths:
        - /usr/sbin
        - /usr/bin
      files:
        - named-checkconf
      skip: true
  register: named_checkconf
