---
- name: Find named-checkzone
  include_tasks:
    named_checkzone: "{{ item }}"
  with_first_found:
    - paths:
        - /usr/sbin
        - /usr/bin
      files:
        - named-checkzone
      skip: true

- name: Find named-checkconf
  include_tasks:
    named_checkconf: "{{ item }}"
  with_first_found:
    - paths:
        - /usr/sbin
        - /usr/bin
      files:
        - named-checkconf
      skip: true
